POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username":"admin",
    "password":"admin",
    "name":"admin",
    "email":"kieudanh.itc@gmail.com",
    "birthday":"30/07/2001"
}